# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-05 01:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_delete_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_image',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_upload_file',
            field=models.FileField(blank=True, null=True, upload_to='user_upload_file'),
        ),
    ]
