# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-05 02:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_remove_userprofile_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('user_upload_file', models.FileField(blank=True, null=True, upload_to='user_upload_file')),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='belong_to',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
