# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-05 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20170705_1040'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=20, null=True)),
                ('user_upload_file', models.FileField(blank=True, null=True, upload_to='./upload/')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
